name: test9999
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: test999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181818'
    - '#777777'
    - '#a7a7a7'
    - '#c3c3c3'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
